// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Attribute struct {
	ID        int64     `json:"id"`
	JobID     int64     `json:"job_id"`
	Name      string    `json:"name"`
	AttrType  string    `json:"attr_type"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type AttributeValue struct {
	ID          int64  `json:"id"`
	AttributeID int64  `json:"attribute_id"`
	Name        string `json:"name"`
	SortOrder   int32  `json:"sort_order"`
}

type Category struct {
	ID        int64         `json:"id"`
	JobID     int64         `json:"job_id"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	Name      string        `json:"name"`
	Level     int32         `json:"level"`
	SortOrder int32         `json:"sort_order"`
	Status    string        `json:"status"`
	CreatedAt time.Time     `json:"created_at"`
}

type EnrichmentCache struct {
	ID        int64           `json:"id"`
	Source    string          `json:"source"`
	QueryKey  string          `json:"query_key"`
	Data      json.RawMessage `json:"data"`
	ExpiresAt time.Time       `json:"expires_at"`
	CreatedAt time.Time       `json:"created_at"`
}

type EntityMapping struct {
	ID           int64          `json:"id"`
	RunID        int64          `json:"run_id"`
	LocalID      int64          `json:"local_id"`
	PlentyID     int64          `json:"plenty_id"`
	EntityType   string         `json:"entity_type"`
	Stage        string         `json:"stage"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Image struct {
	ID          int64          `json:"id"`
	ProductID   int64          `json:"product_id"`
	SourceUrl   string         `json:"source_url"`
	LocalPath   string         `json:"local_path"`
	Position    int32          `json:"position"`
	SourceType  string         `json:"source_type"`
	Attribution sql.NullString `json:"attribution"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Job struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	JobType   string          `json:"job_type"`
	Config    json.RawMessage `json:"config"`
	Status    string          `json:"status"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type OauthToken struct {
	ID           int64     `json:"id"`
	ShopUrl      string    `json:"shop_url"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	TokenType    string    `json:"token_type"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PipelineRun struct {
	ID           int64          `json:"id"`
	JobID        int64          `json:"job_id"`
	Status       string         `json:"status"`
	CurrentStage sql.NullString `json:"current_stage"`
	StartedAt    sql.NullTime   `json:"started_at"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Product struct {
	ID          int64           `json:"id"`
	JobID       int64           `json:"job_id"`
	Name        string          `json:"name"`
	ProductType string          `json:"product_type"`
	BaseData    json.RawMessage `json:"base_data"`
	Status      string          `json:"status"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type ProductCategory struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int64 `json:"category_id"`
}

type Property struct {
	ID           int64     `json:"id"`
	JobID        int64     `json:"job_id"`
	Name         string    `json:"name"`
	PropertyType string    `json:"property_type"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type PropertyText struct {
	ID          int64  `json:"id"`
	VariationID int64  `json:"variation_id"`
	PropertyID  int64  `json:"property_id"`
	Lang        string `json:"lang"`
	Content     string `json:"content"`
}

type QualityScore struct {
	ID         int64           `json:"id"`
	ProductID  int64           `json:"product_id"`
	JobID      int64           `json:"job_id"`
	Overall    string          `json:"overall"`
	TextScore  string          `json:"text_score"`
	ImageScore string          `json:"image_score"`
	DataScore  string          `json:"data_score"`
	Pass       bool            `json:"pass"`
	Details    json.RawMessage `json:"details"`
	CreatedAt  time.Time       `json:"created_at"`
}

type StageState struct {
	ID          int64          `json:"id"`
	RunID       int64          `json:"run_id"`
	StageName   string         `json:"stage_name"`
	Status      string         `json:"status"`
	Processed   int32          `json:"processed"`
	Total       int32          `json:"total"`
	ErrorDetail sql.NullString `json:"error_detail"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type Text struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	Field     string    `json:"field"`
	Lang      string    `json:"lang"`
	Content   string    `json:"content"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Variation struct {
	ID         int64          `json:"id"`
	ProductID  int64          `json:"product_id"`
	Name       string         `json:"name"`
	Sku        string         `json:"sku"`
	Price      sql.NullString `json:"price"`
	Currency   string         `json:"currency"`
	Weight     sql.NullString `json:"weight"`
	WeightUnit string         `json:"weight_unit"`
	Barcode    string         `json:"barcode"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
}

type VariationAttribute struct {
	VariationID      int64 `json:"variation_id"`
	AttributeID      int64 `json:"attribute_id"`
	AttributeValueID int64 `json:"attribute_value_id"`
}

type VariationProperty struct {
	ID          int64          `json:"id"`
	VariationID int64          `json:"variation_id"`
	PropertyID  int64          `json:"property_id"`
	ValueText   sql.NullString `json:"value_text"`
	ValueInt    sql.NullInt64  `json:"value_int"`
	ValueFloat  sql.NullString `json:"value_float"`
}
