// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countFailedByRun = `-- name: CountFailedByRun :one
SELECT COUNT(*) as count
FROM entity_mappings
WHERE run_id = ? AND status = 'failed'
`

func (q *Queries) CountFailedByRun(ctx context.Context, runID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedByRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMappingsByStatus = `-- name: CountMappingsByStatus :many
SELECT entity_type, status, COUNT(*) as count
FROM entity_mappings
WHERE run_id = ?
GROUP BY entity_type, status
`

type CountMappingsByStatusRow struct {
	EntityType string `json:"entity_type"`
	Status     string `json:"status"`
	Count      int64  `json:"count"`
}

func (q *Queries) CountMappingsByStatus(ctx context.Context, runID int64) ([]CountMappingsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countMappingsByStatus, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMappingsByStatusRow{}
	for rows.Next() {
		var i CountMappingsByStatusRow
		if err := rows.Scan(&i.EntityType, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAttribute = `-- name: CreateAttribute :execlastid

INSERT INTO attributes (job_id, name, attr_type, status)
VALUES (?, ?, ?, ?)
`

type CreateAttributeParams struct {
	JobID    int64  `json:"job_id"`
	Name     string `json:"name"`
	AttrType string `json:"attr_type"`
	Status   string `json:"status"`
}

// Attributes (CRUD)
func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAttribute,
		arg.JobID,
		arg.Name,
		arg.AttrType,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createAttributeNameTranslation = `-- name: CreateAttributeNameTranslation :execlastid

INSERT INTO attribute_name_translations (attribute_id, lang, name)
VALUES (?, ?, ?)
`

type CreateAttributeNameTranslationParams struct {
	AttributeID int64  `json:"attribute_id"`
	Lang        string `json:"lang"`
	Name        string `json:"name"`
}

// Attribute Name Translations
func (q *Queries) CreateAttributeNameTranslation(ctx context.Context, arg CreateAttributeNameTranslationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAttributeNameTranslation, arg.AttributeID, arg.Lang, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createAttributeValue = `-- name: CreateAttributeValue :execlastid
INSERT INTO attribute_values (attribute_id, name, sort_order)
VALUES (?, ?, ?)
`

type CreateAttributeValueParams struct {
	AttributeID int64  `json:"attribute_id"`
	Name        string `json:"name"`
	SortOrder   int32  `json:"sort_order"`
}

func (q *Queries) CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAttributeValue, arg.AttributeID, arg.Name, arg.SortOrder)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createAttributeValueTranslation = `-- name: CreateAttributeValueTranslation :execlastid

INSERT INTO attribute_value_translations (attribute_value_id, lang, name)
VALUES (?, ?, ?)
`

type CreateAttributeValueTranslationParams struct {
	AttributeValueID int64  `json:"attribute_value_id"`
	Lang             string `json:"lang"`
	Name             string `json:"name"`
}

// Attribute Value Translations
func (q *Queries) CreateAttributeValueTranslation(ctx context.Context, arg CreateAttributeValueTranslationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAttributeValueTranslation, arg.AttributeValueID, arg.Lang, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createCategory = `-- name: CreateCategory :execlastid

INSERT INTO categories (job_id, parent_id, name, level, sort_order, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	JobID     int64         `json:"job_id"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	Name      string        `json:"name"`
	Level     int32         `json:"level"`
	SortOrder int32         `json:"sort_order"`
	Status    string        `json:"status"`
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCategory,
		arg.JobID,
		arg.ParentID,
		arg.Name,
		arg.Level,
		arg.SortOrder,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createCategoryTranslation = `-- name: CreateCategoryTranslation :execlastid

INSERT INTO category_translations (category_id, lang, name, description)
VALUES (?, ?, ?, ?)
`

type CreateCategoryTranslationParams struct {
	CategoryID  int64  `json:"category_id"`
	Lang        string `json:"lang"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// Category Translations
func (q *Queries) CreateCategoryTranslation(ctx context.Context, arg CreateCategoryTranslationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCategoryTranslation,
		arg.CategoryID,
		arg.Lang,
		arg.Name,
		arg.Description,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createEntityMapping = `-- name: CreateEntityMapping :execlastid

INSERT INTO entity_mappings (run_id, local_id, plenty_id, entity_type, stage, status, error_message)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEntityMappingParams struct {
	RunID        int64          `json:"run_id"`
	LocalID      int64          `json:"local_id"`
	PlentyID     int64          `json:"plenty_id"`
	EntityType   string         `json:"entity_type"`
	Stage        string         `json:"stage"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

// Entity Mappings
func (q *Queries) CreateEntityMapping(ctx context.Context, arg CreateEntityMappingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createEntityMapping,
		arg.RunID,
		arg.LocalID,
		arg.PlentyID,
		arg.EntityType,
		arg.Stage,
		arg.Status,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createGraduatedPrice = `-- name: CreateGraduatedPrice :execlastid

INSERT INTO variation_graduated_prices (variation_id, minimum_quantity, price, rrp)
VALUES (?, ?, ?, ?)
`

type CreateGraduatedPriceParams struct {
	VariationID     int64  `json:"variation_id"`
	MinimumQuantity int32  `json:"minimum_quantity"`
	Price           string `json:"price"`
	Rrp             string `json:"rrp"`
}

// Graduated Prices
func (q *Queries) CreateGraduatedPrice(ctx context.Context, arg CreateGraduatedPriceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGraduatedPrice,
		arg.VariationID,
		arg.MinimumQuantity,
		arg.Price,
		arg.Rrp,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createImage = `-- name: CreateImage :execlastid

INSERT INTO images (product_id, source_url, local_path, position, source_type, attribution, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateImageParams struct {
	ProductID   int64          `json:"product_id"`
	SourceUrl   string         `json:"source_url"`
	LocalPath   string         `json:"local_path"`
	Position    int32          `json:"position"`
	SourceType  string         `json:"source_type"`
	Attribution sql.NullString `json:"attribution"`
	Status      string         `json:"status"`
}

// Images
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createImage,
		arg.ProductID,
		arg.SourceUrl,
		arg.LocalPath,
		arg.Position,
		arg.SourceType,
		arg.Attribution,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createJob = `-- name: CreateJob :execlastid

INSERT INTO jobs (name, job_type, config, status)
VALUES (?, ?, ?, ?)
`

type CreateJobParams struct {
	Name    string          `json:"name"`
	JobType string          `json:"job_type"`
	Config  json.RawMessage `json:"config"`
	Status  string          `json:"status"`
}

// Jobs
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createJob,
		arg.Name,
		arg.JobType,
		arg.Config,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createPipelineRun = `-- name: CreatePipelineRun :execlastid

INSERT INTO pipeline_runs (job_id, status, current_stage)
VALUES (?, ?, ?)
`

type CreatePipelineRunParams struct {
	JobID        int64          `json:"job_id"`
	Status       string         `json:"status"`
	CurrentStage sql.NullString `json:"current_stage"`
}

// Pipeline Runs
func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPipelineRun, arg.JobID, arg.Status, arg.CurrentStage)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createProduct = `-- name: CreateProduct :execlastid

INSERT INTO products (job_id, name, product_type, base_data, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	JobID       int64           `json:"job_id"`
	Name        string          `json:"name"`
	ProductType string          `json:"product_type"`
	BaseData    json.RawMessage `json:"base_data"`
	Status      string          `json:"status"`
}

// Products
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProduct,
		arg.JobID,
		arg.Name,
		arg.ProductType,
		arg.BaseData,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createProductCategory = `-- name: CreateProductCategory :exec
INSERT INTO product_categories (product_id, category_id)
VALUES (?, ?)
`

type CreateProductCategoryParams struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const createProperty = `-- name: CreateProperty :execlastid

INSERT INTO properties (job_id, name, property_type, status)
VALUES (?, ?, ?, ?)
`

type CreatePropertyParams struct {
	JobID        int64  `json:"job_id"`
	Name         string `json:"name"`
	PropertyType string `json:"property_type"`
	Status       string `json:"status"`
}

// Properties
func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProperty,
		arg.JobID,
		arg.Name,
		arg.PropertyType,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createPropertyGroup = `-- name: CreatePropertyGroup :execlastid

INSERT INTO property_groups (job_id, name, status)
VALUES (?, ?, ?)
`

type CreatePropertyGroupParams struct {
	JobID  int64  `json:"job_id"`
	Name   string `json:"name"`
	Status string `json:"status"`
}

// Property Groups
func (q *Queries) CreatePropertyGroup(ctx context.Context, arg CreatePropertyGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPropertyGroup, arg.JobID, arg.Name, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createPropertyGroupTranslation = `-- name: CreatePropertyGroupTranslation :execlastid

INSERT INTO property_group_translations (property_group_id, lang, name)
VALUES (?, ?, ?)
`

type CreatePropertyGroupTranslationParams struct {
	PropertyGroupID int64  `json:"property_group_id"`
	Lang            string `json:"lang"`
	Name            string `json:"name"`
}

// Property Group Translations
func (q *Queries) CreatePropertyGroupTranslation(ctx context.Context, arg CreatePropertyGroupTranslationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPropertyGroupTranslation, arg.PropertyGroupID, arg.Lang, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createPropertyNameTranslation = `-- name: CreatePropertyNameTranslation :execlastid

INSERT INTO property_name_translations (property_id, lang, name)
VALUES (?, ?, ?)
`

type CreatePropertyNameTranslationParams struct {
	PropertyID int64  `json:"property_id"`
	Lang       string `json:"lang"`
	Name       string `json:"name"`
}

// Property Name Translations
func (q *Queries) CreatePropertyNameTranslation(ctx context.Context, arg CreatePropertyNameTranslationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPropertyNameTranslation, arg.PropertyID, arg.Lang, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createPropertyOptionTranslation = `-- name: CreatePropertyOptionTranslation :execlastid

INSERT INTO property_option_translations (property_id, option_key, lang, name)
VALUES (?, ?, ?, ?)
`

type CreatePropertyOptionTranslationParams struct {
	PropertyID int64  `json:"property_id"`
	OptionKey  string `json:"option_key"`
	Lang       string `json:"lang"`
	Name       string `json:"name"`
}

// Property Option Translations
func (q *Queries) CreatePropertyOptionTranslation(ctx context.Context, arg CreatePropertyOptionTranslationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPropertyOptionTranslation,
		arg.PropertyID,
		arg.OptionKey,
		arg.Lang,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createQualityScore = `-- name: CreateQualityScore :execlastid

INSERT INTO quality_scores (product_id, job_id, overall, text_score, image_score, data_score, pass, details)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateQualityScoreParams struct {
	ProductID  int64           `json:"product_id"`
	JobID      int64           `json:"job_id"`
	Overall    string          `json:"overall"`
	TextScore  string          `json:"text_score"`
	ImageScore string          `json:"image_score"`
	DataScore  string          `json:"data_score"`
	Pass       bool            `json:"pass"`
	Details    json.RawMessage `json:"details"`
}

// Quality Scores
func (q *Queries) CreateQualityScore(ctx context.Context, arg CreateQualityScoreParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createQualityScore,
		arg.ProductID,
		arg.JobID,
		arg.Overall,
		arg.TextScore,
		arg.ImageScore,
		arg.DataScore,
		arg.Pass,
		arg.Details,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createStageState = `-- name: CreateStageState :execlastid

INSERT INTO stage_states (run_id, stage_name, status)
VALUES (?, ?, ?)
`

type CreateStageStateParams struct {
	RunID     int64  `json:"run_id"`
	StageName string `json:"stage_name"`
	Status    string `json:"status"`
}

// Stage States
func (q *Queries) CreateStageState(ctx context.Context, arg CreateStageStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createStageState, arg.RunID, arg.StageName, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createText = `-- name: CreateText :execlastid

INSERT INTO texts (product_id, field, lang, content, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateTextParams struct {
	ProductID int64  `json:"product_id"`
	Field     string `json:"field"`
	Lang      string `json:"lang"`
	Content   string `json:"content"`
	Status    string `json:"status"`
}

// Texts
func (q *Queries) CreateText(ctx context.Context, arg CreateTextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createText,
		arg.ProductID,
		arg.Field,
		arg.Lang,
		arg.Content,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createVariation = `-- name: CreateVariation :execlastid

INSERT INTO variations (product_id, name, sku, price, rrp, b2b_price, b2b_rrp, currency, weight, weight_unit, sales_unit, length_mm, width_mm, height_mm, barcode, model, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVariationParams struct {
	ProductID  int64          `json:"product_id"`
	Name       string         `json:"name"`
	Sku        string         `json:"sku"`
	Price      sql.NullString `json:"price"`
	Rrp        sql.NullString `json:"rrp"`
	B2bPrice   sql.NullString `json:"b2b_price"`
	B2bRrp     sql.NullString `json:"b2b_rrp"`
	Currency   string         `json:"currency"`
	Weight     sql.NullString `json:"weight"`
	WeightUnit string         `json:"weight_unit"`
	SalesUnit  string         `json:"sales_unit"`
	LengthMm   int32          `json:"length_mm"`
	WidthMm    int32          `json:"width_mm"`
	HeightMm   int32          `json:"height_mm"`
	Barcode    string         `json:"barcode"`
	Model      string         `json:"model"`
	Status     string         `json:"status"`
}

// Variations
func (q *Queries) CreateVariation(ctx context.Context, arg CreateVariationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVariation,
		arg.ProductID,
		arg.Name,
		arg.Sku,
		arg.Price,
		arg.Rrp,
		arg.B2bPrice,
		arg.B2bRrp,
		arg.Currency,
		arg.Weight,
		arg.WeightUnit,
		arg.SalesUnit,
		arg.LengthMm,
		arg.WidthMm,
		arg.HeightMm,
		arg.Barcode,
		arg.Model,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createVariationAttribute = `-- name: CreateVariationAttribute :exec

INSERT INTO variation_attributes (variation_id, attribute_id, attribute_value_id)
VALUES (?, ?, ?)
`

type CreateVariationAttributeParams struct {
	VariationID      int64 `json:"variation_id"`
	AttributeID      int64 `json:"attribute_id"`
	AttributeValueID int64 `json:"attribute_value_id"`
}

// Variation-Attribute Links
func (q *Queries) CreateVariationAttribute(ctx context.Context, arg CreateVariationAttributeParams) error {
	_, err := q.db.ExecContext(ctx, createVariationAttribute, arg.VariationID, arg.AttributeID, arg.AttributeValueID)
	return err
}

const createVariationProperty = `-- name: CreateVariationProperty :execlastid

INSERT INTO variation_properties (variation_id, property_id, value_text, value_int, value_float)
VALUES (?, ?, ?, ?, ?)
`

type CreateVariationPropertyParams struct {
	VariationID int64          `json:"variation_id"`
	PropertyID  int64          `json:"property_id"`
	ValueText   sql.NullString `json:"value_text"`
	ValueInt    sql.NullInt64  `json:"value_int"`
	ValueFloat  sql.NullString `json:"value_float"`
}

// Variation Properties
func (q *Queries) CreateVariationProperty(ctx context.Context, arg CreateVariationPropertyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVariationProperty,
		arg.VariationID,
		arg.PropertyID,
		arg.ValueText,
		arg.ValueInt,
		arg.ValueFloat,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteExpiredEnrichmentCache = `-- name: DeleteExpiredEnrichmentCache :exec
DELETE FROM enrichment_cache
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredEnrichmentCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredEnrichmentCache)
	return err
}

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens
WHERE shop_url = ?
`

func (q *Queries) DeleteOAuthToken(ctx context.Context, shopUrl string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthToken, shopUrl)
	return err
}

const getAttributeByJobAndName = `-- name: GetAttributeByJobAndName :one
SELECT id, job_id, name, attr_type, status, created_at
FROM attributes
WHERE job_id = ? AND name = ?
LIMIT 1
`

type GetAttributeByJobAndNameParams struct {
	JobID int64  `json:"job_id"`
	Name  string `json:"name"`
}

func (q *Queries) GetAttributeByJobAndName(ctx context.Context, arg GetAttributeByJobAndNameParams) (Attribute, error) {
	row := q.db.QueryRowContext(ctx, getAttributeByJobAndName, arg.JobID, arg.Name)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.AttrType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAttributeValueByAttrAndName = `-- name: GetAttributeValueByAttrAndName :one
SELECT id, attribute_id, name, sort_order
FROM attribute_values
WHERE attribute_id = ? AND name = ?
LIMIT 1
`

type GetAttributeValueByAttrAndNameParams struct {
	AttributeID int64  `json:"attribute_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetAttributeValueByAttrAndName(ctx context.Context, arg GetAttributeValueByAttrAndNameParams) (AttributeValue, error) {
	row := q.db.QueryRowContext(ctx, getAttributeValueByAttrAndName, arg.AttributeID, arg.Name)
	var i AttributeValue
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.Name,
		&i.SortOrder,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, job_id, parent_id, name, level, sort_order, status, created_at
FROM categories
WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.Level,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryByJobAndName = `-- name: GetCategoryByJobAndName :one
SELECT id, job_id, parent_id, name, level, sort_order, status, created_at
FROM categories
WHERE job_id = ? AND name = ?
LIMIT 1
`

type GetCategoryByJobAndNameParams struct {
	JobID int64  `json:"job_id"`
	Name  string `json:"name"`
}

func (q *Queries) GetCategoryByJobAndName(ctx context.Context, arg GetCategoryByJobAndNameParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByJobAndName, arg.JobID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ParentID,
		&i.Name,
		&i.Level,
		&i.SortOrder,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrichmentCache = `-- name: GetEnrichmentCache :one

SELECT id, source, query_key, data, expires_at, created_at
FROM enrichment_cache
WHERE source = ? AND query_key = ? AND expires_at > NOW()
`

type GetEnrichmentCacheParams struct {
	Source   string `json:"source"`
	QueryKey string `json:"query_key"`
}

// Enrichment Cache
func (q *Queries) GetEnrichmentCache(ctx context.Context, arg GetEnrichmentCacheParams) (EnrichmentCache, error) {
	row := q.db.QueryRowContext(ctx, getEnrichmentCache, arg.Source, arg.QueryKey)
	var i EnrichmentCache
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.QueryKey,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEntityMapping = `-- name: GetEntityMapping :one
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE local_id = ? AND entity_type = ? AND run_id = ?
`

type GetEntityMappingParams struct {
	LocalID    int64  `json:"local_id"`
	EntityType string `json:"entity_type"`
	RunID      int64  `json:"run_id"`
}

func (q *Queries) GetEntityMapping(ctx context.Context, arg GetEntityMappingParams) (EntityMapping, error) {
	row := q.db.QueryRowContext(ctx, getEntityMapping, arg.LocalID, arg.EntityType, arg.RunID)
	var i EntityMapping
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LocalID,
		&i.PlentyID,
		&i.EntityType,
		&i.Stage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityMappingByPlentyID = `-- name: GetEntityMappingByPlentyID :one
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE plenty_id = ? AND entity_type = ?
LIMIT 1
`

type GetEntityMappingByPlentyIDParams struct {
	PlentyID   int64  `json:"plenty_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetEntityMappingByPlentyID(ctx context.Context, arg GetEntityMappingByPlentyIDParams) (EntityMapping, error) {
	row := q.db.QueryRowContext(ctx, getEntityMappingByPlentyID, arg.PlentyID, arg.EntityType)
	var i EntityMapping
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LocalID,
		&i.PlentyID,
		&i.EntityType,
		&i.Stage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, name, job_type, config, status, created_at, updated_at
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JobType,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMappingByLocalIDAndType = `-- name: GetMappingByLocalIDAndType :one
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND local_id = ? AND entity_type = ?
`

type GetMappingByLocalIDAndTypeParams struct {
	RunID      int64  `json:"run_id"`
	LocalID    int64  `json:"local_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetMappingByLocalIDAndType(ctx context.Context, arg GetMappingByLocalIDAndTypeParams) (EntityMapping, error) {
	row := q.db.QueryRowContext(ctx, getMappingByLocalIDAndType, arg.RunID, arg.LocalID, arg.EntityType)
	var i EntityMapping
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LocalID,
		&i.PlentyID,
		&i.EntityType,
		&i.Stage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, shop_url, access_token, refresh_token, token_type, expires_at, created_at, updated_at
FROM oauth_tokens
WHERE shop_url = ?
`

func (q *Queries) GetOAuthToken(ctx context.Context, shopUrl string) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, getOAuthToken, shopUrl)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.ShopUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineRun = `-- name: GetPipelineRun :one
SELECT id, job_id, status, current_stage, started_at, completed_at, error_message, created_at, updated_at
FROM pipeline_runs
WHERE id = ?
`

func (q *Queries) GetPipelineRun(ctx context.Context, id int64) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getPipelineRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CurrentStage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineRunByJobLatest = `-- name: GetPipelineRunByJobLatest :one
SELECT id, job_id, status, current_stage, started_at, completed_at, error_message, created_at, updated_at
FROM pipeline_runs
WHERE job_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPipelineRunByJobLatest(ctx context.Context, jobID int64) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getPipelineRunByJobLatest, jobID)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CurrentStage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, job_id, name, product_type, base_data, status, created_at, updated_at
FROM products
WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.ProductType,
		&i.BaseData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPropertyByJobAndName = `-- name: GetPropertyByJobAndName :one
SELECT id, job_id, name, property_type, status, created_at
FROM properties
WHERE job_id = ? AND name = ?
`

type GetPropertyByJobAndNameParams struct {
	JobID int64  `json:"job_id"`
	Name  string `json:"name"`
}

type GetPropertyByJobAndNameRow struct {
	ID           int64     `json:"id"`
	JobID        int64     `json:"job_id"`
	Name         string    `json:"name"`
	PropertyType string    `json:"property_type"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetPropertyByJobAndName(ctx context.Context, arg GetPropertyByJobAndNameParams) (GetPropertyByJobAndNameRow, error) {
	row := q.db.QueryRowContext(ctx, getPropertyByJobAndName, arg.JobID, arg.Name)
	var i GetPropertyByJobAndNameRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.PropertyType,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPropertyGroupByJob = `-- name: GetPropertyGroupByJob :one
SELECT id, job_id, name, status, created_at
FROM property_groups
WHERE job_id = ?
LIMIT 1
`

func (q *Queries) GetPropertyGroupByJob(ctx context.Context, jobID int64) (PropertyGroup, error) {
	row := q.db.QueryRowContext(ctx, getPropertyGroupByJob, jobID)
	var i PropertyGroup
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getQualityScoreByProduct = `-- name: GetQualityScoreByProduct :one
SELECT id, product_id, job_id, overall, text_score, image_score, data_score, pass, details, created_at
FROM quality_scores
WHERE product_id = ?
`

func (q *Queries) GetQualityScoreByProduct(ctx context.Context, productID int64) (QualityScore, error) {
	row := q.db.QueryRowContext(ctx, getQualityScoreByProduct, productID)
	var i QualityScore
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.JobID,
		&i.Overall,
		&i.TextScore,
		&i.ImageScore,
		&i.DataScore,
		&i.Pass,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getStageState = `-- name: GetStageState :one
SELECT id, run_id, stage_name, status, processed, total, error_detail, started_at, completed_at
FROM stage_states
WHERE run_id = ? AND stage_name = ?
`

type GetStageStateParams struct {
	RunID     int64  `json:"run_id"`
	StageName string `json:"stage_name"`
}

func (q *Queries) GetStageState(ctx context.Context, arg GetStageStateParams) (StageState, error) {
	row := q.db.QueryRowContext(ctx, getStageState, arg.RunID, arg.StageName)
	var i StageState
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageName,
		&i.Status,
		&i.Processed,
		&i.Total,
		&i.ErrorDetail,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTextByProductFieldLang = `-- name: GetTextByProductFieldLang :one
SELECT id, product_id, field, lang, content, status, created_at, updated_at
FROM texts
WHERE product_id = ? AND field = ? AND lang = ?
`

type GetTextByProductFieldLangParams struct {
	ProductID int64  `json:"product_id"`
	Field     string `json:"field"`
	Lang      string `json:"lang"`
}

func (q *Queries) GetTextByProductFieldLang(ctx context.Context, arg GetTextByProductFieldLangParams) (Text, error) {
	row := q.db.QueryRowContext(ctx, getTextByProductFieldLang, arg.ProductID, arg.Field, arg.Lang)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Field,
		&i.Lang,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPropertyOptionTranslations = `-- name: ListAllPropertyOptionTranslations :many
SELECT id, property_id, option_key, lang, name
FROM property_option_translations
WHERE property_id = ?
ORDER BY option_key, lang
`

func (q *Queries) ListAllPropertyOptionTranslations(ctx context.Context, propertyID int64) ([]PropertyOptionTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listAllPropertyOptionTranslations, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PropertyOptionTranslation{}
	for rows.Next() {
		var i PropertyOptionTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.OptionKey,
			&i.Lang,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributeNameTranslations = `-- name: ListAttributeNameTranslations :many
SELECT id, attribute_id, lang, name
FROM attribute_name_translations
WHERE attribute_id = ?
ORDER BY lang
`

func (q *Queries) ListAttributeNameTranslations(ctx context.Context, attributeID int64) ([]AttributeNameTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listAttributeNameTranslations, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeNameTranslation{}
	for rows.Next() {
		var i AttributeNameTranslation
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Lang,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributeValueTranslations = `-- name: ListAttributeValueTranslations :many
SELECT id, attribute_value_id, lang, name
FROM attribute_value_translations
WHERE attribute_value_id = ?
ORDER BY lang
`

func (q *Queries) ListAttributeValueTranslations(ctx context.Context, attributeValueID int64) ([]AttributeValueTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listAttributeValueTranslations, attributeValueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeValueTranslation{}
	for rows.Next() {
		var i AttributeValueTranslation
		if err := rows.Scan(
			&i.ID,
			&i.AttributeValueID,
			&i.Lang,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributeValuesByAttribute = `-- name: ListAttributeValuesByAttribute :many
SELECT id, attribute_id, name, sort_order
FROM attribute_values
WHERE attribute_id = ?
ORDER BY sort_order
`

func (q *Queries) ListAttributeValuesByAttribute(ctx context.Context, attributeID int64) ([]AttributeValue, error) {
	rows, err := q.db.QueryContext(ctx, listAttributeValuesByAttribute, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeValue{}
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributesByJob = `-- name: ListAttributesByJob :many
SELECT id, job_id, name, attr_type, status, created_at
FROM attributes
WHERE job_id = ?
ORDER BY created_at
`

func (q *Queries) ListAttributesByJob(ctx context.Context, jobID int64) ([]Attribute, error) {
	rows, err := q.db.QueryContext(ctx, listAttributesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attribute{}
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.AttrType,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByJob = `-- name: ListCategoriesByJob :many
SELECT id, job_id, parent_id, name, level, sort_order, status, created_at
FROM categories
WHERE job_id = ?
ORDER BY level, sort_order
`

func (q *Queries) ListCategoriesByJob(ctx context.Context, jobID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.Level,
			&i.SortOrder,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryIDsByProduct = `-- name: ListCategoryIDsByProduct :many
SELECT category_id FROM product_categories
WHERE product_id = ?
ORDER BY category_id
`

func (q *Queries) ListCategoryIDsByProduct(ctx context.Context, productID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryIDsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var category_id int64
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryTranslations = `-- name: ListCategoryTranslations :many
SELECT id, category_id, lang, name, description
FROM category_translations
WHERE category_id = ?
ORDER BY lang
`

func (q *Queries) ListCategoryTranslations(ctx context.Context, categoryID int64) ([]CategoryTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listCategoryTranslations, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryTranslation{}
	for rows.Next() {
		var i CategoryTranslation
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Lang,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatedMappingsByRunAndType = `-- name: ListCreatedMappingsByRunAndType :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND entity_type = ? AND status = 'created'
ORDER BY created_at
`

type ListCreatedMappingsByRunAndTypeParams struct {
	RunID      int64  `json:"run_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) ListCreatedMappingsByRunAndType(ctx context.Context, arg ListCreatedMappingsByRunAndTypeParams) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listCreatedMappingsByRunAndType, arg.RunID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctPropertyValues = `-- name: ListDistinctPropertyValues :many
SELECT DISTINCT vp.value_text
FROM variation_properties vp
WHERE vp.property_id = ? AND vp.value_text IS NOT NULL
ORDER BY vp.value_text
`

func (q *Queries) ListDistinctPropertyValues(ctx context.Context, propertyID int64) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctPropertyValues, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var value_text sql.NullString
		if err := rows.Scan(&value_text); err != nil {
			return nil, err
		}
		items = append(items, value_text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityMappingsByRun = `-- name: ListEntityMappingsByRun :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND entity_type = ?
ORDER BY created_at
`

type ListEntityMappingsByRunParams struct {
	RunID      int64  `json:"run_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) ListEntityMappingsByRun(ctx context.Context, arg ListEntityMappingsByRunParams) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listEntityMappingsByRun, arg.RunID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedMappingsByRun = `-- name: ListFailedMappingsByRun :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND status = 'failed'
ORDER BY created_at
`

func (q *Queries) ListFailedMappingsByRun(ctx context.Context, runID int64) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listFailedMappingsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedQualityScoresByJob = `-- name: ListFailedQualityScoresByJob :many
SELECT id, product_id, job_id, overall, text_score, image_score, data_score, pass, details, created_at
FROM quality_scores
WHERE job_id = ? AND pass = FALSE
ORDER BY overall ASC
`

func (q *Queries) ListFailedQualityScoresByJob(ctx context.Context, jobID int64) ([]QualityScore, error) {
	rows, err := q.db.QueryContext(ctx, listFailedQualityScoresByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityScore{}
	for rows.Next() {
		var i QualityScore
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.JobID,
			&i.Overall,
			&i.TextScore,
			&i.ImageScore,
			&i.DataScore,
			&i.Pass,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraduatedPricesByVariation = `-- name: ListGraduatedPricesByVariation :many
SELECT id, variation_id, minimum_quantity, price, rrp
FROM variation_graduated_prices
WHERE variation_id = ?
ORDER BY minimum_quantity
`

func (q *Queries) ListGraduatedPricesByVariation(ctx context.Context, variationID int64) ([]VariationGraduatedPrice, error) {
	rows, err := q.db.QueryContext(ctx, listGraduatedPricesByVariation, variationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariationGraduatedPrice{}
	for rows.Next() {
		var i VariationGraduatedPrice
		if err := rows.Scan(
			&i.ID,
			&i.VariationID,
			&i.MinimumQuantity,
			&i.Price,
			&i.Rrp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByProduct = `-- name: ListImagesByProduct :many
SELECT id, product_id, source_url, local_path, position, source_type, attribution, status, created_at
FROM images
WHERE product_id = ?
ORDER BY position
`

func (q *Queries) ListImagesByProduct(ctx context.Context, productID int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SourceUrl,
			&i.LocalPath,
			&i.Position,
			&i.SourceType,
			&i.Attribution,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedMappingsByRun = `-- name: ListOrphanedMappingsByRun :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND status = 'orphaned'
ORDER BY created_at
`

func (q *Queries) ListOrphanedMappingsByRun(ctx context.Context, runID int64) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanedMappingsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineRunsByJob = `-- name: ListPipelineRunsByJob :many
SELECT id, job_id, status, current_stage, started_at, completed_at, error_message, created_at, updated_at
FROM pipeline_runs
WHERE job_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListPipelineRunsByJob(ctx context.Context, jobID int64) ([]PipelineRun, error) {
	rows, err := q.db.QueryContext(ctx, listPipelineRunsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Status,
			&i.CurrentStage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByJob = `-- name: ListProductsByJob :many
SELECT id, job_id, name, product_type, base_data, status, created_at, updated_at
FROM products
WHERE job_id = ?
ORDER BY created_at
`

func (q *Queries) ListProductsByJob(ctx context.Context, jobID int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.ProductType,
			&i.BaseData,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByJobAndStatus = `-- name: ListProductsByJobAndStatus :many
SELECT id, job_id, name, product_type, base_data, status, created_at, updated_at
FROM products
WHERE job_id = ? AND status = ?
ORDER BY created_at
`

type ListProductsByJobAndStatusParams struct {
	JobID  int64  `json:"job_id"`
	Status string `json:"status"`
}

func (q *Queries) ListProductsByJobAndStatus(ctx context.Context, arg ListProductsByJobAndStatusParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByJobAndStatus, arg.JobID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.ProductType,
			&i.BaseData,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesByJob = `-- name: ListPropertiesByJob :many
SELECT id, job_id, name, property_type, status, created_at
FROM properties
WHERE job_id = ?
ORDER BY created_at
`

type ListPropertiesByJobRow struct {
	ID           int64     `json:"id"`
	JobID        int64     `json:"job_id"`
	Name         string    `json:"name"`
	PropertyType string    `json:"property_type"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListPropertiesByJob(ctx context.Context, jobID int64) ([]ListPropertiesByJobRow, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesByJobRow{}
	for rows.Next() {
		var i ListPropertiesByJobRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.PropertyType,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertyGroupTranslations = `-- name: ListPropertyGroupTranslations :many
SELECT id, property_group_id, lang, name
FROM property_group_translations
WHERE property_group_id = ?
ORDER BY lang
`

func (q *Queries) ListPropertyGroupTranslations(ctx context.Context, propertyGroupID int64) ([]PropertyGroupTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listPropertyGroupTranslations, propertyGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PropertyGroupTranslation{}
	for rows.Next() {
		var i PropertyGroupTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyGroupID,
			&i.Lang,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertyNameTranslations = `-- name: ListPropertyNameTranslations :many
SELECT id, property_id, lang, name
FROM property_name_translations
WHERE property_id = ?
ORDER BY lang
`

func (q *Queries) ListPropertyNameTranslations(ctx context.Context, propertyID int64) ([]PropertyNameTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listPropertyNameTranslations, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PropertyNameTranslation{}
	for rows.Next() {
		var i PropertyNameTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Lang,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertyOptionTranslations = `-- name: ListPropertyOptionTranslations :many
SELECT id, property_id, option_key, lang, name
FROM property_option_translations
WHERE property_id = ? AND option_key = ?
ORDER BY lang
`

type ListPropertyOptionTranslationsParams struct {
	PropertyID int64  `json:"property_id"`
	OptionKey  string `json:"option_key"`
}

func (q *Queries) ListPropertyOptionTranslations(ctx context.Context, arg ListPropertyOptionTranslationsParams) ([]PropertyOptionTranslation, error) {
	rows, err := q.db.QueryContext(ctx, listPropertyOptionTranslations, arg.PropertyID, arg.OptionKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PropertyOptionTranslation{}
	for rows.Next() {
		var i PropertyOptionTranslation
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.OptionKey,
			&i.Lang,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityScoresByJob = `-- name: ListQualityScoresByJob :many
SELECT id, product_id, job_id, overall, text_score, image_score, data_score, pass, details, created_at
FROM quality_scores
WHERE job_id = ?
ORDER BY overall DESC
`

func (q *Queries) ListQualityScoresByJob(ctx context.Context, jobID int64) ([]QualityScore, error) {
	rows, err := q.db.QueryContext(ctx, listQualityScoresByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualityScore{}
	for rows.Next() {
		var i QualityScore
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.JobID,
			&i.Overall,
			&i.TextScore,
			&i.ImageScore,
			&i.DataScore,
			&i.Pass,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJobs = `-- name: ListRecentJobs :many
SELECT id, name, job_type, config, status, created_at, updated_at
FROM jobs
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListRecentJobs(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRecentJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.JobType,
			&i.Config,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageStatesByRun = `-- name: ListStageStatesByRun :many
SELECT id, run_id, stage_name, status, processed, total, error_detail, started_at, completed_at
FROM stage_states
WHERE run_id = ?
ORDER BY stage_name
`

func (q *Queries) ListStageStatesByRun(ctx context.Context, runID int64) ([]StageState, error) {
	rows, err := q.db.QueryContext(ctx, listStageStatesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageState{}
	for rows.Next() {
		var i StageState
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageName,
			&i.Status,
			&i.Processed,
			&i.Total,
			&i.ErrorDetail,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextsByProduct = `-- name: ListTextsByProduct :many
SELECT id, product_id, field, lang, content, status, created_at, updated_at
FROM texts
WHERE product_id = ?
ORDER BY field, lang
`

func (q *Queries) ListTextsByProduct(ctx context.Context, productID int64) ([]Text, error) {
	rows, err := q.db.QueryContext(ctx, listTextsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Text{}
	for rows.Next() {
		var i Text
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Field,
			&i.Lang,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariationAttributesByVariation = `-- name: ListVariationAttributesByVariation :many
SELECT variation_id, attribute_id, attribute_value_id
FROM variation_attributes
WHERE variation_id = ?
ORDER BY attribute_id
`

func (q *Queries) ListVariationAttributesByVariation(ctx context.Context, variationID int64) ([]VariationAttribute, error) {
	rows, err := q.db.QueryContext(ctx, listVariationAttributesByVariation, variationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariationAttribute{}
	for rows.Next() {
		var i VariationAttribute
		if err := rows.Scan(&i.VariationID, &i.AttributeID, &i.AttributeValueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariationPropertiesByVariation = `-- name: ListVariationPropertiesByVariation :many
SELECT vp.id, vp.variation_id, vp.property_id, vp.value_text, vp.value_int, vp.value_float,
       p.name as property_name, p.property_type
FROM variation_properties vp
JOIN properties p ON p.id = vp.property_id
WHERE vp.variation_id = ?
ORDER BY p.name
`

type ListVariationPropertiesByVariationRow struct {
	ID           int64          `json:"id"`
	VariationID  int64          `json:"variation_id"`
	PropertyID   int64          `json:"property_id"`
	ValueText    sql.NullString `json:"value_text"`
	ValueInt     sql.NullInt64  `json:"value_int"`
	ValueFloat   sql.NullString `json:"value_float"`
	PropertyName string         `json:"property_name"`
	PropertyType string         `json:"property_type"`
}

func (q *Queries) ListVariationPropertiesByVariation(ctx context.Context, variationID int64) ([]ListVariationPropertiesByVariationRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariationPropertiesByVariation, variationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariationPropertiesByVariationRow{}
	for rows.Next() {
		var i ListVariationPropertiesByVariationRow
		if err := rows.Scan(
			&i.ID,
			&i.VariationID,
			&i.PropertyID,
			&i.ValueText,
			&i.ValueInt,
			&i.ValueFloat,
			&i.PropertyName,
			&i.PropertyType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariationsByProduct = `-- name: ListVariationsByProduct :many
SELECT id, product_id, name, sku, price, currency, weight, weight_unit, barcode, status, created_at, sales_unit, rrp, length_mm, width_mm, height_mm, b2b_price, b2b_rrp, model
FROM variations
WHERE product_id = ?
ORDER BY created_at
`

func (q *Queries) ListVariationsByProduct(ctx context.Context, productID int64) ([]Variation, error) {
	rows, err := q.db.QueryContext(ctx, listVariationsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variation{}
	for rows.Next() {
		var i Variation
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.Currency,
			&i.Weight,
			&i.WeightUnit,
			&i.Barcode,
			&i.Status,
			&i.CreatedAt,
			&i.SalesUnit,
			&i.Rrp,
			&i.LengthMm,
			&i.WidthMm,
			&i.HeightMm,
			&i.B2bPrice,
			&i.B2bRrp,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariationsWithoutPropertiesByJob = `-- name: ListVariationsWithoutPropertiesByJob :many

SELECT v.id as variation_id, v.product_id, v.name as variation_name,
       p.name as product_name, p.product_type
FROM variations v
JOIN products p ON v.product_id = p.id
WHERE p.job_id = ?
AND NOT EXISTS (SELECT 1 FROM variation_properties vp WHERE vp.variation_id = v.id)
ORDER BY v.id
`

type ListVariationsWithoutPropertiesByJobRow struct {
	VariationID   int64  `json:"variation_id"`
	ProductID     int64  `json:"product_id"`
	VariationName string `json:"variation_name"`
	ProductName   string `json:"product_name"`
	ProductType   string `json:"product_type"`
}

// Variations Without Properties (for backfill)
func (q *Queries) ListVariationsWithoutPropertiesByJob(ctx context.Context, jobID int64) ([]ListVariationsWithoutPropertiesByJobRow, error) {
	rows, err := q.db.QueryContext(ctx, listVariationsWithoutPropertiesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariationsWithoutPropertiesByJobRow{}
	for rows.Next() {
		var i ListVariationsWithoutPropertiesByJobRow
		if err := rows.Scan(
			&i.VariationID,
			&i.ProductID,
			&i.VariationName,
			&i.ProductName,
			&i.ProductType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupCategoryRegistry = `-- name: LookupCategoryRegistry :one

SELECT id, name, parent_name, plenty_id, created_at
FROM category_registry
WHERE name = ? AND parent_name = ?
`

type LookupCategoryRegistryParams struct {
	Name       string `json:"name"`
	ParentName string `json:"parent_name"`
}

// Category Registry (cross-job reuse)
func (q *Queries) LookupCategoryRegistry(ctx context.Context, arg LookupCategoryRegistryParams) (CategoryRegistry, error) {
	row := q.db.QueryRowContext(ctx, lookupCategoryRegistry, arg.Name, arg.ParentName)
	var i CategoryRegistry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentName,
		&i.PlentyID,
		&i.CreatedAt,
	)
	return i, err
}

const registerCategory = `-- name: RegisterCategory :execlastid
INSERT INTO category_registry (name, parent_name, plenty_id)
VALUES (?, ?, ?)
`

type RegisterCategoryParams struct {
	Name       string `json:"name"`
	ParentName string `json:"parent_name"`
	PlentyID   int64  `json:"plenty_id"`
}

func (q *Queries) RegisterCategory(ctx context.Context, arg RegisterCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, registerCategory, arg.Name, arg.ParentName, arg.PlentyID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const resetFailedMappingsForRetry = `-- name: ResetFailedMappingsForRetry :exec
UPDATE entity_mappings
SET status = 'pending', error_message = NULL, updated_at = NOW()
WHERE run_id = ? AND status = 'failed'
`

func (q *Queries) ResetFailedMappingsForRetry(ctx context.Context, runID int64) error {
	_, err := q.db.ExecContext(ctx, resetFailedMappingsForRetry, runID)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs SET status = ? WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.Status, arg.ID)
	return err
}

const updateMappingStatus = `-- name: UpdateMappingStatus :exec
UPDATE entity_mappings
SET status = ?, plenty_id = ?, error_message = ?, updated_at = NOW()
WHERE id = ?
`

type UpdateMappingStatusParams struct {
	Status       string         `json:"status"`
	PlentyID     int64          `json:"plenty_id"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateMappingStatus(ctx context.Context, arg UpdateMappingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMappingStatus,
		arg.Status,
		arg.PlentyID,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updatePipelineRunCompleted = `-- name: UpdatePipelineRunCompleted :exec
UPDATE pipeline_runs
SET status = ?, current_stage = ?, completed_at = NOW(), updated_at = NOW()
WHERE id = ?
`

type UpdatePipelineRunCompletedParams struct {
	Status       string         `json:"status"`
	CurrentStage sql.NullString `json:"current_stage"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdatePipelineRunCompleted(ctx context.Context, arg UpdatePipelineRunCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunCompleted, arg.Status, arg.CurrentStage, arg.ID)
	return err
}

const updatePipelineRunStatus = `-- name: UpdatePipelineRunStatus :exec
UPDATE pipeline_runs
SET status = ?, current_stage = ?, error_message = ?, updated_at = NOW()
WHERE id = ?
`

type UpdatePipelineRunStatusParams struct {
	Status       string         `json:"status"`
	CurrentStage sql.NullString `json:"current_stage"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunStatus,
		arg.Status,
		arg.CurrentStage,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updatePropertyGroupID = `-- name: UpdatePropertyGroupID :exec
UPDATE properties SET property_group_id = ? WHERE id = ?
`

type UpdatePropertyGroupIDParams struct {
	PropertyGroupID sql.NullInt64 `json:"property_group_id"`
	ID              int64         `json:"id"`
}

func (q *Queries) UpdatePropertyGroupID(ctx context.Context, arg UpdatePropertyGroupIDParams) error {
	_, err := q.db.ExecContext(ctx, updatePropertyGroupID, arg.PropertyGroupID, arg.ID)
	return err
}

const updateStageState = `-- name: UpdateStageState :exec
UPDATE stage_states
SET status = ?, processed = ?, total = ?
WHERE id = ?
`

type UpdateStageStateParams struct {
	Status    string `json:"status"`
	Processed int32  `json:"processed"`
	Total     int32  `json:"total"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateStageState(ctx context.Context, arg UpdateStageStateParams) error {
	_, err := q.db.ExecContext(ctx, updateStageState,
		arg.Status,
		arg.Processed,
		arg.Total,
		arg.ID,
	)
	return err
}

const updateStageStateTimestamps = `-- name: UpdateStageStateTimestamps :exec
UPDATE stage_states
SET status = ?, processed = ?, total = ?, started_at = ?, completed_at = ?
WHERE id = ?
`

type UpdateStageStateTimestampsParams struct {
	Status      string       `json:"status"`
	Processed   int32        `json:"processed"`
	Total       int32        `json:"total"`
	StartedAt   sql.NullTime `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateStageStateTimestamps(ctx context.Context, arg UpdateStageStateTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, updateStageStateTimestamps,
		arg.Status,
		arg.Processed,
		arg.Total,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}

const upsertEnrichmentCache = `-- name: UpsertEnrichmentCache :exec
INSERT INTO enrichment_cache (source, query_key, data, expires_at)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    data = VALUES(data),
    expires_at = VALUES(expires_at)
`

type UpsertEnrichmentCacheParams struct {
	Source    string          `json:"source"`
	QueryKey  string          `json:"query_key"`
	Data      json.RawMessage `json:"data"`
	ExpiresAt time.Time       `json:"expires_at"`
}

func (q *Queries) UpsertEnrichmentCache(ctx context.Context, arg UpsertEnrichmentCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertEnrichmentCache,
		arg.Source,
		arg.QueryKey,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :exec

INSERT INTO oauth_tokens (shop_url, access_token, refresh_token, token_type, expires_at)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    access_token = VALUES(access_token),
    refresh_token = VALUES(refresh_token),
    token_type = VALUES(token_type),
    expires_at = VALUES(expires_at)
`

type UpsertOAuthTokenParams struct {
	ShopUrl      string    `json:"shop_url"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	TokenType    string    `json:"token_type"`
	ExpiresAt    time.Time `json:"expires_at"`
}

// OAuth Tokens
func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertOAuthToken,
		arg.ShopUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.ExpiresAt,
	)
	return err
}
