// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countFailedByRun = `-- name: CountFailedByRun :one
SELECT COUNT(*) as count
FROM entity_mappings
WHERE run_id = ? AND status = 'failed'
`

func (q *Queries) CountFailedByRun(ctx context.Context, runID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailedByRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMappingsByStatus = `-- name: CountMappingsByStatus :many
SELECT entity_type, status, COUNT(*) as count
FROM entity_mappings
WHERE run_id = ?
GROUP BY entity_type, status
`

type CountMappingsByStatusRow struct {
	EntityType string `json:"entity_type"`
	Status     string `json:"status"`
	Count      int64  `json:"count"`
}

func (q *Queries) CountMappingsByStatus(ctx context.Context, runID int64) ([]CountMappingsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countMappingsByStatus, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMappingsByStatusRow{}
	for rows.Next() {
		var i CountMappingsByStatusRow
		if err := rows.Scan(&i.EntityType, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens
WHERE shop_url = ?
`

func (q *Queries) DeleteOAuthToken(ctx context.Context, shopUrl string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthToken, shopUrl)
	return err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, shop_url, access_token, refresh_token, token_type, expires_at, created_at, updated_at
FROM oauth_tokens
WHERE shop_url = ?
`

func (q *Queries) GetOAuthToken(ctx context.Context, shopUrl string) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, getOAuthToken, shopUrl)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.ShopUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :exec
INSERT INTO oauth_tokens (shop_url, access_token, refresh_token, token_type, expires_at)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    access_token = VALUES(access_token),
    refresh_token = VALUES(refresh_token),
    token_type = VALUES(token_type),
    expires_at = VALUES(expires_at)
`

type UpsertOAuthTokenParams struct {
	ShopUrl      string    `json:"shop_url"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	TokenType    string    `json:"token_type"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertOAuthToken,
		arg.ShopUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.ExpiresAt,
	)
	return err
}

const createCategory = `-- name: CreateCategory :execlastid

INSERT INTO categories (job_id, parent_id, name, level, sort_order, status)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	JobID     int64         `json:"job_id"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	Name      string        `json:"name"`
	Level     int32         `json:"level"`
	SortOrder int32         `json:"sort_order"`
	Status    string        `json:"status"`
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCategory,
		arg.JobID,
		arg.ParentID,
		arg.Name,
		arg.Level,
		arg.SortOrder,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createEntityMapping = `-- name: CreateEntityMapping :execlastid

INSERT INTO entity_mappings (run_id, local_id, plenty_id, entity_type, stage, status, error_message)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEntityMappingParams struct {
	RunID        int64          `json:"run_id"`
	LocalID      int64          `json:"local_id"`
	PlentyID     int64          `json:"plenty_id"`
	EntityType   string         `json:"entity_type"`
	Stage        string         `json:"stage"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

// Entity Mappings
func (q *Queries) CreateEntityMapping(ctx context.Context, arg CreateEntityMappingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createEntityMapping,
		arg.RunID,
		arg.LocalID,
		arg.PlentyID,
		arg.EntityType,
		arg.Stage,
		arg.Status,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createImage = `-- name: CreateImage :execlastid

INSERT INTO images (product_id, source_url, local_path, position, source_type, attribution, status)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateImageParams struct {
	ProductID   int64          `json:"product_id"`
	SourceUrl   string         `json:"source_url"`
	LocalPath   string         `json:"local_path"`
	Position    int32          `json:"position"`
	SourceType  string         `json:"source_type"`
	Attribution sql.NullString `json:"attribution"`
	Status      string         `json:"status"`
}

// Images
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createImage,
		arg.ProductID,
		arg.SourceUrl,
		arg.LocalPath,
		arg.Position,
		arg.SourceType,
		arg.Attribution,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createJob = `-- name: CreateJob :execlastid

INSERT INTO jobs (name, job_type, config, status)
VALUES (?, ?, ?, ?)
`

type CreateJobParams struct {
	Name    string          `json:"name"`
	JobType string          `json:"job_type"`
	Config  json.RawMessage `json:"config"`
	Status  string          `json:"status"`
}

// Jobs
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createJob,
		arg.Name,
		arg.JobType,
		arg.Config,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createPipelineRun = `-- name: CreatePipelineRun :execlastid

INSERT INTO pipeline_runs (job_id, status, current_stage)
VALUES (?, ?, ?)
`

type CreatePipelineRunParams struct {
	JobID        int64          `json:"job_id"`
	Status       string         `json:"status"`
	CurrentStage sql.NullString `json:"current_stage"`
}

// Pipeline Runs
func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPipelineRun, arg.JobID, arg.Status, arg.CurrentStage)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createProduct = `-- name: CreateProduct :execlastid

INSERT INTO products (job_id, name, product_type, base_data, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	JobID       int64           `json:"job_id"`
	Name        string          `json:"name"`
	ProductType string          `json:"product_type"`
	BaseData    json.RawMessage `json:"base_data"`
	Status      string          `json:"status"`
}

// Products
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProduct,
		arg.JobID,
		arg.Name,
		arg.ProductType,
		arg.BaseData,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createStageState = `-- name: CreateStageState :execlastid

INSERT INTO stage_states (run_id, stage_name, status)
VALUES (?, ?, ?)
`

type CreateStageStateParams struct {
	RunID     int64  `json:"run_id"`
	StageName string `json:"stage_name"`
	Status    string `json:"status"`
}

// Stage States
func (q *Queries) CreateStageState(ctx context.Context, arg CreateStageStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createStageState, arg.RunID, arg.StageName, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createText = `-- name: CreateText :execlastid

INSERT INTO texts (product_id, field, lang, content, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateTextParams struct {
	ProductID int64  `json:"product_id"`
	Field     string `json:"field"`
	Lang      string `json:"lang"`
	Content   string `json:"content"`
	Status    string `json:"status"`
}

// Texts
func (q *Queries) CreateText(ctx context.Context, arg CreateTextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createText,
		arg.ProductID,
		arg.Field,
		arg.Lang,
		arg.Content,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createVariation = `-- name: CreateVariation :execlastid

INSERT INTO variations (product_id, name, sku, price, currency, weight, weight_unit, barcode, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVariationParams struct {
	ProductID  int64          `json:"product_id"`
	Name       string         `json:"name"`
	Sku        string         `json:"sku"`
	Price      sql.NullString `json:"price"`
	Currency   string         `json:"currency"`
	Weight     sql.NullString `json:"weight"`
	WeightUnit string         `json:"weight_unit"`
	Barcode    string         `json:"barcode"`
	Status     string         `json:"status"`
}

// Variations
func (q *Queries) CreateVariation(ctx context.Context, arg CreateVariationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVariation,
		arg.ProductID,
		arg.Name,
		arg.Sku,
		arg.Price,
		arg.Currency,
		arg.Weight,
		arg.WeightUnit,
		arg.Barcode,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getEntityMapping = `-- name: GetEntityMapping :one
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE local_id = ? AND entity_type = ? AND run_id = ?
`

type GetEntityMappingParams struct {
	LocalID    int64  `json:"local_id"`
	EntityType string `json:"entity_type"`
	RunID      int64  `json:"run_id"`
}

func (q *Queries) GetEntityMapping(ctx context.Context, arg GetEntityMappingParams) (EntityMapping, error) {
	row := q.db.QueryRowContext(ctx, getEntityMapping, arg.LocalID, arg.EntityType, arg.RunID)
	var i EntityMapping
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LocalID,
		&i.PlentyID,
		&i.EntityType,
		&i.Stage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityMappingByPlentyID = `-- name: GetEntityMappingByPlentyID :one
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE plenty_id = ? AND entity_type = ?
LIMIT 1
`

type GetEntityMappingByPlentyIDParams struct {
	PlentyID   int64  `json:"plenty_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetEntityMappingByPlentyID(ctx context.Context, arg GetEntityMappingByPlentyIDParams) (EntityMapping, error) {
	row := q.db.QueryRowContext(ctx, getEntityMappingByPlentyID, arg.PlentyID, arg.EntityType)
	var i EntityMapping
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LocalID,
		&i.PlentyID,
		&i.EntityType,
		&i.Stage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMappingByLocalIDAndType = `-- name: GetMappingByLocalIDAndType :one
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND local_id = ? AND entity_type = ?
`

type GetMappingByLocalIDAndTypeParams struct {
	RunID      int64  `json:"run_id"`
	LocalID    int64  `json:"local_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) GetMappingByLocalIDAndType(ctx context.Context, arg GetMappingByLocalIDAndTypeParams) (EntityMapping, error) {
	row := q.db.QueryRowContext(ctx, getMappingByLocalIDAndType, arg.RunID, arg.LocalID, arg.EntityType)
	var i EntityMapping
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LocalID,
		&i.PlentyID,
		&i.EntityType,
		&i.Stage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, name, job_type, config, status, created_at, updated_at
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JobType,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineRun = `-- name: GetPipelineRun :one
SELECT id, job_id, status, current_stage, started_at, completed_at, error_message, created_at, updated_at
FROM pipeline_runs
WHERE id = ?
`

func (q *Queries) GetPipelineRun(ctx context.Context, id int64) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getPipelineRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CurrentStage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineRunByJobLatest = `-- name: GetPipelineRunByJobLatest :one
SELECT id, job_id, status, current_stage, started_at, completed_at, error_message, created_at, updated_at
FROM pipeline_runs
WHERE job_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPipelineRunByJobLatest(ctx context.Context, jobID int64) (PipelineRun, error) {
	row := q.db.QueryRowContext(ctx, getPipelineRunByJobLatest, jobID)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.CurrentStage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, job_id, name, product_type, base_data, status, created_at, updated_at
FROM products
WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.ProductType,
		&i.BaseData,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStageState = `-- name: GetStageState :one
SELECT id, run_id, stage_name, status, processed, total, error_detail, started_at, completed_at
FROM stage_states
WHERE run_id = ? AND stage_name = ?
`

type GetStageStateParams struct {
	RunID     int64  `json:"run_id"`
	StageName string `json:"stage_name"`
}

func (q *Queries) GetStageState(ctx context.Context, arg GetStageStateParams) (StageState, error) {
	row := q.db.QueryRowContext(ctx, getStageState, arg.RunID, arg.StageName)
	var i StageState
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageName,
		&i.Status,
		&i.Processed,
		&i.Total,
		&i.ErrorDetail,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTextByProductFieldLang = `-- name: GetTextByProductFieldLang :one
SELECT id, product_id, field, lang, content, status, created_at, updated_at
FROM texts
WHERE product_id = ? AND field = ? AND lang = ?
`

type GetTextByProductFieldLangParams struct {
	ProductID int64  `json:"product_id"`
	Field     string `json:"field"`
	Lang      string `json:"lang"`
}

func (q *Queries) GetTextByProductFieldLang(ctx context.Context, arg GetTextByProductFieldLangParams) (Text, error) {
	row := q.db.QueryRowContext(ctx, getTextByProductFieldLang, arg.ProductID, arg.Field, arg.Lang)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Field,
		&i.Lang,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByJob = `-- name: ListCategoriesByJob :many
SELECT id, job_id, parent_id, name, level, sort_order, status, created_at
FROM categories
WHERE job_id = ?
ORDER BY level, sort_order
`

func (q *Queries) ListCategoriesByJob(ctx context.Context, jobID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ParentID,
			&i.Name,
			&i.Level,
			&i.SortOrder,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributeValuesByAttribute = `-- name: ListAttributeValuesByAttribute :many
SELECT id, attribute_id, name, sort_order
FROM attribute_values
WHERE attribute_id = ?
ORDER BY sort_order
`

func (q *Queries) ListAttributeValuesByAttribute(ctx context.Context, attributeID int64) ([]AttributeValue, error) {
	rows, err := q.db.QueryContext(ctx, listAttributeValuesByAttribute, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeValue{}
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Name,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributesByJob = `-- name: ListAttributesByJob :many
SELECT id, job_id, name, attr_type, status, created_at
FROM attributes
WHERE job_id = ?
ORDER BY created_at
`

func (q *Queries) ListAttributesByJob(ctx context.Context, jobID int64) ([]Attribute, error) {
	rows, err := q.db.QueryContext(ctx, listAttributesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attribute{}
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.AttrType,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatedMappingsByRunAndType = `-- name: ListCreatedMappingsByRunAndType :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND entity_type = ? AND status = 'created'
ORDER BY created_at
`

type ListCreatedMappingsByRunAndTypeParams struct {
	RunID      int64  `json:"run_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) ListCreatedMappingsByRunAndType(ctx context.Context, arg ListCreatedMappingsByRunAndTypeParams) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listCreatedMappingsByRunAndType, arg.RunID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityMappingsByRun = `-- name: ListEntityMappingsByRun :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND entity_type = ?
ORDER BY created_at
`

type ListEntityMappingsByRunParams struct {
	RunID      int64  `json:"run_id"`
	EntityType string `json:"entity_type"`
}

func (q *Queries) ListEntityMappingsByRun(ctx context.Context, arg ListEntityMappingsByRunParams) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listEntityMappingsByRun, arg.RunID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedMappingsByRun = `-- name: ListFailedMappingsByRun :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND status = 'failed'
ORDER BY created_at
`

func (q *Queries) ListFailedMappingsByRun(ctx context.Context, runID int64) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listFailedMappingsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedMappingsByRun = `-- name: ListOrphanedMappingsByRun :many
SELECT id, run_id, local_id, plenty_id, entity_type, stage, status, error_message, created_at, updated_at
FROM entity_mappings
WHERE run_id = ? AND status = 'orphaned'
ORDER BY created_at
`

func (q *Queries) ListOrphanedMappingsByRun(ctx context.Context, runID int64) ([]EntityMapping, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanedMappingsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityMapping{}
	for rows.Next() {
		var i EntityMapping
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LocalID,
			&i.PlentyID,
			&i.EntityType,
			&i.Stage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByProduct = `-- name: ListImagesByProduct :many
SELECT id, product_id, source_url, local_path, position, source_type, attribution, status, created_at
FROM images
WHERE product_id = ?
ORDER BY position
`

func (q *Queries) ListImagesByProduct(ctx context.Context, productID int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SourceUrl,
			&i.LocalPath,
			&i.Position,
			&i.SourceType,
			&i.Attribution,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineRunsByJob = `-- name: ListPipelineRunsByJob :many
SELECT id, job_id, status, current_stage, started_at, completed_at, error_message, created_at, updated_at
FROM pipeline_runs
WHERE job_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListPipelineRunsByJob(ctx context.Context, jobID int64) ([]PipelineRun, error) {
	rows, err := q.db.QueryContext(ctx, listPipelineRunsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Status,
			&i.CurrentStage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByJob = `-- name: ListProductsByJob :many
SELECT id, job_id, name, product_type, base_data, status, created_at, updated_at
FROM products
WHERE job_id = ?
ORDER BY created_at
`

func (q *Queries) ListProductsByJob(ctx context.Context, jobID int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.ProductType,
			&i.BaseData,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByJobAndStatus = `-- name: ListProductsByJobAndStatus :many
SELECT id, job_id, name, product_type, base_data, status, created_at, updated_at
FROM products
WHERE job_id = ? AND status = ?
ORDER BY created_at
`

type ListProductsByJobAndStatusParams struct {
	JobID  int64  `json:"job_id"`
	Status string `json:"status"`
}

func (q *Queries) ListProductsByJobAndStatus(ctx context.Context, arg ListProductsByJobAndStatusParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByJobAndStatus, arg.JobID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.ProductType,
			&i.BaseData,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropertiesByJob = `-- name: ListPropertiesByJob :many
SELECT id, job_id, name, property_type, status, created_at
FROM properties
WHERE job_id = ?
ORDER BY created_at
`

func (q *Queries) ListPropertiesByJob(ctx context.Context, jobID int64) ([]Property, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Property{}
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.PropertyType,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageStatesByRun = `-- name: ListStageStatesByRun :many
SELECT id, run_id, stage_name, status, processed, total, error_detail, started_at, completed_at
FROM stage_states
WHERE run_id = ?
ORDER BY stage_name
`

func (q *Queries) ListStageStatesByRun(ctx context.Context, runID int64) ([]StageState, error) {
	rows, err := q.db.QueryContext(ctx, listStageStatesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StageState{}
	for rows.Next() {
		var i StageState
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageName,
			&i.Status,
			&i.Processed,
			&i.Total,
			&i.ErrorDetail,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextsByProduct = `-- name: ListTextsByProduct :many
SELECT id, product_id, field, lang, content, status, created_at, updated_at
FROM texts
WHERE product_id = ?
ORDER BY field, lang
`

func (q *Queries) ListTextsByProduct(ctx context.Context, productID int64) ([]Text, error) {
	rows, err := q.db.QueryContext(ctx, listTextsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Text{}
	for rows.Next() {
		var i Text
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Field,
			&i.Lang,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariationsByProduct = `-- name: ListVariationsByProduct :many
SELECT id, product_id, name, sku, price, currency, weight, weight_unit, barcode, status, created_at
FROM variations
WHERE product_id = ?
ORDER BY created_at
`

func (q *Queries) ListVariationsByProduct(ctx context.Context, productID int64) ([]Variation, error) {
	rows, err := q.db.QueryContext(ctx, listVariationsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variation{}
	for rows.Next() {
		var i Variation
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.Currency,
			&i.Weight,
			&i.WeightUnit,
			&i.Barcode,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFailedMappingsForRetry = `-- name: ResetFailedMappingsForRetry :exec
UPDATE entity_mappings
SET status = 'pending', error_message = NULL, updated_at = NOW()
WHERE run_id = ? AND status = 'failed'
`

func (q *Queries) ResetFailedMappingsForRetry(ctx context.Context, runID int64) error {
	_, err := q.db.ExecContext(ctx, resetFailedMappingsForRetry, runID)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs SET status = ? WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.Status, arg.ID)
	return err
}

const updateMappingStatus = `-- name: UpdateMappingStatus :exec
UPDATE entity_mappings
SET status = ?, plenty_id = ?, error_message = ?, updated_at = NOW()
WHERE id = ?
`

type UpdateMappingStatusParams struct {
	Status       string         `json:"status"`
	PlentyID     int64          `json:"plenty_id"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateMappingStatus(ctx context.Context, arg UpdateMappingStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMappingStatus,
		arg.Status,
		arg.PlentyID,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updatePipelineRunStatus = `-- name: UpdatePipelineRunStatus :exec
UPDATE pipeline_runs
SET status = ?, current_stage = ?, error_message = ?, updated_at = NOW()
WHERE id = ?
`

type UpdatePipelineRunStatusParams struct {
	Status       string         `json:"status"`
	CurrentStage sql.NullString `json:"current_stage"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunStatus,
		arg.Status,
		arg.CurrentStage,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const updatePipelineRunCompleted = `-- name: UpdatePipelineRunCompleted :exec
UPDATE pipeline_runs
SET status = ?, current_stage = ?, completed_at = NOW(), updated_at = NOW()
WHERE id = ?
`

type UpdatePipelineRunCompletedParams struct {
	Status       string         `json:"status"`
	CurrentStage sql.NullString `json:"current_stage"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdatePipelineRunCompleted(ctx context.Context, arg UpdatePipelineRunCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunCompleted,
		arg.Status,
		arg.CurrentStage,
		arg.ID,
	)
	return err
}

const updateStageState = `-- name: UpdateStageState :exec
UPDATE stage_states
SET status = ?, processed = ?, total = ?
WHERE id = ?
`

type UpdateStageStateParams struct {
	Status    string `json:"status"`
	Processed int32  `json:"processed"`
	Total     int32  `json:"total"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateStageState(ctx context.Context, arg UpdateStageStateParams) error {
	_, err := q.db.ExecContext(ctx, updateStageState,
		arg.Status,
		arg.Processed,
		arg.Total,
		arg.ID,
	)
	return err
}

const updateStageStateTimestamps = `-- name: UpdateStageStateTimestamps :exec
UPDATE stage_states
SET status = ?, processed = ?, total = ?, started_at = ?, completed_at = ?
WHERE id = ?
`

type UpdateStageStateTimestampsParams struct {
	Status      string       `json:"status"`
	Processed   int32        `json:"processed"`
	Total       int32        `json:"total"`
	StartedAt   sql.NullTime `json:"started_at"`
	CompletedAt sql.NullTime `json:"completed_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateStageStateTimestamps(ctx context.Context, arg UpdateStageStateTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, updateStageStateTimestamps,
		arg.Status,
		arg.Processed,
		arg.Total,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
