// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	CountMappingsByStatus(ctx context.Context, runID int64) ([]CountMappingsByStatusRow, error)
	// Categories
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error)
	// Entity Mappings
	CreateEntityMapping(ctx context.Context, arg CreateEntityMappingParams) (int64, error)
	// Images
	CreateImage(ctx context.Context, arg CreateImageParams) (int64, error)
	// Jobs
	CreateJob(ctx context.Context, arg CreateJobParams) (int64, error)
	// Pipeline Runs
	CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (int64, error)
	// Products
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	// Stage States
	CreateStageState(ctx context.Context, arg CreateStageStateParams) (int64, error)
	// Texts
	CreateText(ctx context.Context, arg CreateTextParams) (int64, error)
	// Variations
	CreateVariation(ctx context.Context, arg CreateVariationParams) (int64, error)
	GetEntityMapping(ctx context.Context, arg GetEntityMappingParams) (EntityMapping, error)
	GetEntityMappingByPlentyID(ctx context.Context, arg GetEntityMappingByPlentyIDParams) (EntityMapping, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetPipelineRun(ctx context.Context, id int64) (PipelineRun, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetStageState(ctx context.Context, arg GetStageStateParams) (StageState, error)
	GetTextByProductFieldLang(ctx context.Context, arg GetTextByProductFieldLangParams) (Text, error)
	ListCategoriesByJob(ctx context.Context, jobID int64) ([]Category, error)
	ListEntityMappingsByRun(ctx context.Context, arg ListEntityMappingsByRunParams) ([]EntityMapping, error)
	ListFailedMappingsByRun(ctx context.Context, runID int64) ([]EntityMapping, error)
	ListImagesByProduct(ctx context.Context, productID int64) ([]Image, error)
	ListPipelineRunsByJob(ctx context.Context, jobID int64) ([]PipelineRun, error)
	ListProductsByJob(ctx context.Context, jobID int64) ([]Product, error)
	ListStageStatesByRun(ctx context.Context, runID int64) ([]StageState, error)
	ListTextsByProduct(ctx context.Context, productID int64) ([]Text, error)
	ListVariationsByProduct(ctx context.Context, productID int64) ([]Variation, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateMappingStatus(ctx context.Context, arg UpdateMappingStatusParams) error
	UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) error
	UpdateStageState(ctx context.Context, arg UpdateStageStateParams) error
}

var _ Querier = (*Queries)(nil)
