// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	CountFailedByRun(ctx context.Context, runID int64) (int64, error)
	CountMappingsByStatus(ctx context.Context, runID int64) ([]CountMappingsByStatusRow, error)
	// Categories
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error)
	// Entity Mappings
	CreateEntityMapping(ctx context.Context, arg CreateEntityMappingParams) (int64, error)
	// Images
	CreateImage(ctx context.Context, arg CreateImageParams) (int64, error)
	// Jobs
	CreateJob(ctx context.Context, arg CreateJobParams) (int64, error)
	// Pipeline Runs
	CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (int64, error)
	// Products
	CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error)
	// Stage States
	CreateStageState(ctx context.Context, arg CreateStageStateParams) (int64, error)
	// Texts
	CreateText(ctx context.Context, arg CreateTextParams) (int64, error)
	// Variations
	CreateVariation(ctx context.Context, arg CreateVariationParams) (int64, error)
	DeleteOAuthToken(ctx context.Context, shopUrl string) error
	GetEntityMapping(ctx context.Context, arg GetEntityMappingParams) (EntityMapping, error)
	GetEntityMappingByPlentyID(ctx context.Context, arg GetEntityMappingByPlentyIDParams) (EntityMapping, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetMappingByLocalIDAndType(ctx context.Context, arg GetMappingByLocalIDAndTypeParams) (EntityMapping, error)
	GetOAuthToken(ctx context.Context, shopUrl string) (OauthToken, error)
	GetPipelineRun(ctx context.Context, id int64) (PipelineRun, error)
	GetPipelineRunByJobLatest(ctx context.Context, jobID int64) (PipelineRun, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetStageState(ctx context.Context, arg GetStageStateParams) (StageState, error)
	GetTextByProductFieldLang(ctx context.Context, arg GetTextByProductFieldLangParams) (Text, error)
	ListAttributeValuesByAttribute(ctx context.Context, attributeID int64) ([]AttributeValue, error)
	ListAttributesByJob(ctx context.Context, jobID int64) ([]Attribute, error)
	ListCategoriesByJob(ctx context.Context, jobID int64) ([]Category, error)
	ListCategoryIDsByProduct(ctx context.Context, productID int64) ([]int64, error)
	ListCreatedMappingsByRunAndType(ctx context.Context, arg ListCreatedMappingsByRunAndTypeParams) ([]EntityMapping, error)
	ListEntityMappingsByRun(ctx context.Context, arg ListEntityMappingsByRunParams) ([]EntityMapping, error)
	ListFailedMappingsByRun(ctx context.Context, runID int64) ([]EntityMapping, error)
	ListImagesByProduct(ctx context.Context, productID int64) ([]Image, error)
	ListOrphanedMappingsByRun(ctx context.Context, runID int64) ([]EntityMapping, error)
	ListPipelineRunsByJob(ctx context.Context, jobID int64) ([]PipelineRun, error)
	ListProductsByJob(ctx context.Context, jobID int64) ([]Product, error)
	ListProductsByJobAndStatus(ctx context.Context, arg ListProductsByJobAndStatusParams) ([]Product, error)
	ListPropertiesByJob(ctx context.Context, jobID int64) ([]Property, error)
	ListRecentJobs(ctx context.Context, limit int32) ([]Job, error)
	ListStageStatesByRun(ctx context.Context, runID int64) ([]StageState, error)
	ListTextsByProduct(ctx context.Context, productID int64) ([]Text, error)
	ListVariationsByProduct(ctx context.Context, productID int64) ([]Variation, error)
	ResetFailedMappingsForRetry(ctx context.Context, runID int64) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateMappingStatus(ctx context.Context, arg UpdateMappingStatusParams) error
	UpdatePipelineRunCompleted(ctx context.Context, arg UpdatePipelineRunCompletedParams) error
	UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) error
	UpdateStageState(ctx context.Context, arg UpdateStageStateParams) error
	UpdateStageStateTimestamps(ctx context.Context, arg UpdateStageStateTimestampsParams) error
	// OAuth Tokens
	UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) error
}

var _ Querier = (*Queries)(nil)
